apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dishhome-ingress
  namespace: dishhome
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-rpm: "5000"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.dishhome.com.np
        - portal.dishhome.com.np
        - admin.dishhome.com.np
      secretName: dishhome-tls
  rules:
    - host: api.dishhome.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dishhome-api
                port:
                  number: 80
    - host: portal.dishhome.com.np
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dishhome-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dishhome-portal
                port:
                  number: 80
    - host: admin.dishhome.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dishhome-api
                port:
                  number: 80
